<?php

declare(strict_types=1);

use Accredify\JsonLd\JsonLdProcessor;
use Accredify\JsonLd\Tests\Algorithms\Characterization\Support\BundledContextLoader;

/*
|--------------------------------------------------------------------------
| Characterization tests
|--------------------------------------------------------------------------
| Pins the *current* (lifted-and-shifted) expander output against a set
| of snapshots that were generated by running VC's pre-extraction
| JsonLdProcessor::expand() over the same inputs.
|
| These are NOT spec-conformance tests. They lock in VC's quirky
| behaviour - ksort/sort/escapeString ordering, partial IRI expansion,
| xsd:string collapse - so that Phase 4 PRs which refactor expansion
| can:
|   1. See exactly which fixtures change, and
|   2. Decide PR-by-PR whether each change is intentional spec correction
|      or accidental regression.
|
| WHEN A PHASE 4 PR FAILS A CHARACTERIZATION TEST:
| - Open the fixture diff. If the new output is more spec-correct, update
|   the fixture in the same PR (it stops being a "VC snapshot" and starts
|   being a "v0.x snapshot").
| - Pair the change with the corresponding update in the VC repo's
|   RDFC-10 + signed-credential test fixtures, otherwise existing signed
|   credentials will fail to verify against the new expand chain.
*/

dataset('characterization-fixtures', [
    'sample_obv3',
    'minimal_vcv2',
    'inline_context',
]);

/**
 * @return array<mixed>
 */
function loadFixture(string $name, string $kind): array
{
    $path = __DIR__."/fixtures/{$name}_{$kind}.json";
    if (! is_file($path)) {
        throw new RuntimeException("Missing fixture: {$path}");
    }

    /** @var array<mixed> $decoded */
    $decoded = json_decode(
        (string) file_get_contents($path),
        associative: true,
        flags: JSON_THROW_ON_ERROR,
    );

    return $decoded;
}

it('matches the VC v0 expander snapshot for fixture {0}', function (string $name) {
    $input = loadFixture($name, 'input');
    $expected = loadFixture($name, 'expected');

    $loader = new BundledContextLoader;
    $actual = (new JsonLdProcessor($loader))->expand($input)->toArray();

    expect($actual)->toEqual($expected);
})->with('characterization-fixtures');
