<?php

declare(strict_types=1);

use Accredify\JsonLd\JsonLdProcessor;
use Accredify\JsonLd\Tests\Interop\Support\FixtureDocumentLoader;
use Accredify\JsonLd\Tests\Interop\Support\NQuadsDataset;

/*
|--------------------------------------------------------------------------
| Cross-implementation interop corpus
|--------------------------------------------------------------------------
| Compares this processor's RDF output against goldens generated by
| jsonld.js (the reference implementation) over realistic VC / VP documents.
|
| This is the safety net the W3C conformance suite does NOT provide: the
| suite has no fixture where an embedded node @context defines a type-scoped
| context (the PR #38 bug shape), and internal round-trips cannot catch a
| processor that is consistently wrong — both sides recompute the same wrong
| quads, and only an external verifier sees the signature break. Each golden
| here is the quad set a conformant eddsa-rdfc-2022 signer/verifier derives.
|
| Regenerate goldens with ./tests/Interop/regenerate.sh after changing a
| fixture; review golden diffs like code.
*/

/**
 * Cases where this processor KNOWINGLY diverges from jsonld.js, keyed by
 * case name => reason. Same xfail semantics as the W3C KnownBlockers list: a
 * listed case that still diverges is SKIPPED, a listed case that starts
 * matching FAILS so the entry (and its workaround) cannot outlive the fix.
 */
const INTEROP_KNOWN_DEVIATIONS = [
    'vc-context-null-isolation' => 'Expansion::activateTypeScopedContexts() falls back to the DOCUMENT-level context when resolving a node type, so a presentation-level type-scoped context (Individual) wrongly activates inside a credential isolated by the VC 2.0 `verifiableCredential` @context:null reset. Per spec (and jsonld.js) the isolated credential must not see it. Remove the documentBase fallback to fix.',
];

dataset('interop-cases', function () {
    $dirs = glob(__DIR__.'/fixtures/cases/*', GLOB_ONLYDIR);
    foreach ($dirs ?: [] as $dir) {
        yield basename($dir) => [basename($dir)];
    }
});

it('produces the same RDF dataset as jsonld.js', function (string $case) {
    $dir = __DIR__.'/fixtures/cases/'.$case;

    /** @var array<array-key, mixed> $input */
    $input = json_decode((string) file_get_contents($dir.'/input.jsonld'), true, flags: JSON_THROW_ON_ERROR);
    $expected = (string) file_get_contents($dir.'/expected.nq');

    $deviationReason = INTEROP_KNOWN_DEVIATIONS[$case] ?? null;

    $actual = (new JsonLdProcessor(new FixtureDocumentLoader))->toRdf($input)->toNQuads();
    $matches = NQuadsDataset::equivalent($actual, $expected);

    if ($deviationReason !== null) {
        if ($matches) {
            $this->fail("{$case} is on the known-deviations list but now matches jsonld.js — remove it from INTEROP_KNOWN_DEVIATIONS.");
        }
        $this->markTestSkipped("known deviation from jsonld.js — {$case}: {$deviationReason}");
    }

    expect($matches)->toBeTrue(
        "RDF dataset differs from the jsonld.js golden for '{$case}'"
        ." (quads only in golden are prefixed '-', quads only in our output '+'):\n"
        .NQuadsDataset::diff($actual, $expected),
    );
})->with('interop-cases');
